//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Bashlykova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoservice
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Balance { get; set; }
        public int SkladID { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
